apiVersion: v1
kind: Pod
metadata:
  name: custom-apache
  labels:
    app: custom-apache
  annotations:
    enableLogging: "true"
    fluentbit.io/parser: custom-apache
spec:
  containers:
    - name: custom-apache
      image: edsiper/apache_logs