podAnnotations:
  fluentbit.io/exclude: "true"

config:
  inputs: |
    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        multiline.parser    docker, cri
        Tag                 kube.*
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        Read_from_Head      False
        Refresh_Interval    5

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [FILTER]
        Name    grep
        Match   kube.*
        Regex   kubernetes['annotations']['enableLogging'] true
  outputs: |
    [OUTPUT]
        Name  stdout
        Match kube.*

  customParsers: |
    [PARSER]
        Name        custom-apache
        Format      regex
        Regex       ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$

